export default [
  {
    key: 'avatar1',
    text: 'avatar1',
    value: '/avatar/avatar1.svg',
    image: { avatar: true, src: '/avatar/avatar1.svg' },
  },
  {
    key: 'avatar2',
    text: 'avatar2',
    value: '/avatar/avatar2.svg',
    image: { avatar: true, src: '/avatar/avatar2.svg' },
  },
  {
    key: 'avatar3',
    text: 'avatar3',
    value: '/avatar/avatar3.svg',
    image: { avatar: true, src: '/avatar/avatar3.svg' },
  },
  {
    key: 'avatar4',
    text: 'avatar4',
    value: '/avatar/avatar4.svg',
    image: { avatar: true, src: '/avatar/avatar4.svg' },
  },
  {
    key: 'avatar5',
    text: 'avatar5',
    value: '/avatar/avatar5.svg',
    image: { avatar: true, src: '/avatar/avatar5.svg' },
  },
  {
    key: 'avatar6',
    text: 'avatar6',
    value: '/avatar/avatar6.svg',
    image: { avatar: true, src: '/avatar/avatar6.svg' },
  },
  {
    key: 'avatar7',
    text: 'avatar7',
    value: '/avatar/avatar7.svg',
    image: { avatar: true, src: '/avatar/avatar7.svg' },
  },
  {
    key: 'avatar8',
    text: 'avatar8',
    value: '/avatar/avatar8.svg',
    image: { avatar: true, src: '/avatar/avatar8.svg' },
  },
  {
    key: 'avatar9',
    text: 'avatar9',
    value: '/avatar/avatar9.svg',
    image: { avatar: true, src: '/avatar/avatar9.svg' },
  },
  {
    key: 'avatar10',
    text: 'avatar10',
    value: '/avatar/avatar10.svg',
    image: { avatar: true, src: '/avatar/avatar10.svg' },
  },
  {
    key: 'avatar11',
    text: 'avatar11',
    value: '/avatar/avatar11.svg',
    image: { avatar: true, src: '/avatar/avatar11.svg' },
  },
  {
    key: 'avatar12',
    text: 'avatar12',
    value: '/avatar/avatar12.svg',
    image: { avatar: true, src: '/avatar/avatar12.svg' },
  },
  {
    key: 'avatar13',
    text: 'avatar13',
    value: '/avatar/avatar13.svg',
    image: { avatar: true, src: '/avatar/avatar13.svg' },
  },
  {
    key: 'avatar14',
    text: 'avatar14',
    value: '/avatar/avatar14.svg',
    image: { avatar: true, src: '/avatar/avatar14.svg' },
  },
  {
    key: 'avatar15',
    text: 'avatar15',
    value: '/avatar/avatar15.svg',
    image: { avatar: true, src: '/avatar/avatar15.svg' },
  },
  {
    key: 'avatar16',
    text: 'avatar16',
    value: '/avatar/avatar16.svg',
    image: { avatar: true, src: '/avatar/avatar16.svg' },
  },
];
